name: buy-it

services:
  app:
    container_name: buy-it-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    env_file:
      - .env
    init: true # This helps with signal handling
    extra_hosts:
      - "localhost:127.0.0.1"

  dev:
    container_name: buy-it-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
    env_file:
      - .env
    init: true # This helps with signal handling
    extra_hosts:
      - "localhost:127.0.0.1"
    volumes:
      - .:/app
