// Stub for Konva Global.js
export const Konva = {
  _isUnminified: true,
  isBrowser: true,
  _parseUA: () => ({}),
  autoDrawEnabled: true,
  enableTrace: () => {},
  showWarnings: true,
  capturePointerEventsEnabled: false,
  listenClickTap: true,
  inDblClickWindow: false,
  pixelRatio: 1,
  dragDistance: 3,
  angleDeg: true,
  showDevTools: false,
  shapes: {},
  names: {},
  isDragging: () => false,
  isDragReady: false,
  document: typeof document !== 'undefined' ? document : {},
  _mouseListenClick: false,
  _touchListenClick: false,
  _pointerListenClick: false,
  _mouseInDblClickWindow: false,
  _touchInDblClickWindow: false,
  _pointerInDblClickWindow: false,
  _inDblClickWindow: false,
  _dblClickFunction: null,
  version: '8.4.3'
};
